export const headerNames = {
  "YRSdePjzzfs-fVVUM6blNja": {
    name: "Case assessment-Lab tests",
    values: [
      "S.No.",
      "NPHL Sample ID",
      "Event Id",
      "Event Date",
      "Name of the ART site",
      "Name",
      "Client Code",
      "Date of ART Start",
      "Sex",
      "Age at Visit",
      "VL Sample Collection Date",
      "VL Test Date",
      "VL Test Result",
      "VL Suppression status",
      "Remarks",
    ],
  },
  "YRSdePjzzfs-URSqGzzlYoM": {
    name: "HCV Treatment Card",
    values: [
      "S.No.",
      "NPHL Sample ID",
      "Event Id",
      "Event Date",
      "Name of the ART site",
      "Name",
      "Client Code",
      "Date of ART Start",
      "Sex",
      "Age at Visit",
      "HCV RNA test Date",
      "HCV RNA test result",
      "HCV RNA Detectable Undetectable",
      "Remarks",
    ],
  },
  "DgAKrnlkpHc-h7UjZ5YiX0D": {
    name: "EID and Treatment Details",
    values: [
      "S.No.",
      "NPHL Sample ID",
      "Event Id",
      "Event Date",
      "Name of the ART site",
      "Name",
      "Client Code",
      "Date of ART Start",
      "Sex",
      "Infant",
      "Age of Infant",
      "EID Sample Collection Date",
      "Date of DNA PCR test done",
      "DNA PCR test result",
      "Assay 1 (Rapid Test 1)",
      "Assay 2 (Rapid Test 2)",
      "Assay 3 (Rapid Test 3)",
      "Remarks",
    ],
  },
};
export const rowList = {
  fVVUM6blNja: [
    "nphlId",
    "eventId",
    "eventDate",
    "orgUnitName",
    "gVGIL7DJp4b",
    "drKkLxaGFwv",
    "medicalHistory",
    "TN7r3ws7IG9",
    "zTwMKXGt0xF",
    "fVVUM6blNja",
    "X5R866cglGE",
    "ji97ypBaP2i",
    "rkjZKfO3IPA",
    "",
  ],
  URSqGzzlYoM: [
    "nphlId",
    "eventId",
    "eventDate",
    "orgUnitName",
    "gVGIL7DJp4b",
    "drKkLxaGFwv",
    "medicalHistory",
    "TN7r3ws7IG9",
    "zTwMKXGt0xF",
    "URSqGzzlYoM",
    "jhxkkzooMh9",
    "HsQWo6bMHCl",
    "",
  ],
  h7UjZ5YiX0D: {
    isObj: true,
    h7UjZ5YiX0D: [
      "nphlId",
      "eventId",
      "eventDate",
      "orgUnitName",
      "gVGIL7DJp4b",
      "drKkLxaGFwv",
      "medicalHistory",
      "TN7r3ws7IG9",
      "Infant1",
      "jZcv83TS94J",
      "h7UjZ5YiX0D",
      "zq0pAQE9K8G",
      "h7k7HK13PQg",
      "XclUI4t6pT0",
      "FndSYKGPdi8",
      "whZhaobDhPC",
      "",
    ],
    GEqbUeytrHY: [
      "nphlId",
      "eventId",
      "eventDate",
      "orgUnitName",
      "gVGIL7DJp4b",
      "drKkLxaGFwv",
      "medicalHistory",
      "TN7r3ws7IG9",
      "Infant2",
      "wPdfLc82N6n",
      "GEqbUeytrHY",
      "tf2JirA33L9",
      "DOjaIyENQmx",
      "zZr2UowoxmE",
      "vZDqMGUL8MM",
      "kb8EQv651ii",
      "",
    ],
    ZzlWdUjXGiL: [
      "nphlId",
      "eventId",
      "eventDate",
      "orgUnitName",
      "gVGIL7DJp4b",
      "drKkLxaGFwv",
      "medicalHistory",
      "TN7r3ws7IG9",
      "Infant3",
      "PsACLTd5Q6D",
      "ZzlWdUjXGiL",
      "IN47b900K5R",
      "yICLjp5Rb41",
      "CsoHGbXpKD8",
      "DzUmNQe45aD",
      "zX8lfGiu5A1",
      "",
    ],
  },
};
