import React, { PureComponent } from "react";
import axios from "axios";
import DynamicComponent from "../dynamicComponent/dynamicComponent";
import { OrgUnitTree } from "@hisp-amr/org-unit-tree";
import { useDataQuery } from "@dhis2/app-runtime";
const onError = (error) => console.error(error);
class HomeComponet extends React.Component {
  constructor() {
    super();
    this.state = {
      orgUnit: "",
    };
    this.onSelect = this.onSelect.bind(this);
  }
  onSelect(selected) {
    this.setState({ orgUnit: selected });
  }

  getEvents() {
    var dataValue = [];
    return axios
      .get(
        `../../../api/events.json?orgUnit=ANGhR1pa8I5&ouMode=DESCENDANTS&startDate=2020-01-01&endDate=2020-04-30&paging=false&order=eventDate:des`
      )
      .then((resp) => {
        resp.data.events.forEach(function (arrayItem, index) {
          var dataSetElements = {};
          var dataValueList = [];
          dataSetElements.eventDate = arrayItem["eventDate"];
          dataSetElements.orgUnit = arrayItem["orgUnit"];
          dataSetElements.program = arrayItem["program"];
          for (const dataValEle in arrayItem["dataValues"]) {
            var dataElementsValue = {};
            var dataElement =
              arrayItem["dataValues"][dataValEle]["dataElement"];
            var dataValues = arrayItem["dataValues"][dataValEle]["value"];
            dataElementsValue[dataElement] = dataValues;
            dataValueList.push(dataElementsValue);
          }
          dataSetElements.Elements = dataValueList;
          dataValue.push(dataSetElements);
        });
        var allEvents = JSON.stringify(dataValue);
        return allEvents;
        // export default allEvents;
      });
  }

  getPrograms() {
    axios
      .get(`../../../api/programs.json?paging=false&fielda=id,name`)
      .then((response) => {
        console.log("PROGRAMMS " + JSON.stringify(response.data));
      });
  }

  async getResult() {
    var result = await this.getEvents();
    var dataElementsEvent = [];
    result = JSON.parse(result);
    if (result) {
      result.forEach(function (arrayItem, index) {
        // Promise.all(arrayItem["Elements"]).then(function () {
        //   dataElementsEvent.push(arrayItem["Elements"]);
        // });

        for (const a in arrayItem["Elements"]) {
          dataElementsEvent.push(String(Object.keys(arrayItem["Elements"][a])));
        }
      });

      var returndata = {
        listGrid: {
          metaData: {},
          subtitle: "data element with category option combo",
          width: 9,
          title: "DataElementCOC",
          height: 201468,
          headers: [
            {
              hidden: false,
              meta: false,
              name: "string_agg",
              column: "string_agg",
              type: "java.lang.String",
            },
            {
              hidden: false,
              meta: false,
              name: "deid",
              column: "deid",
              type: "java.lang.String",
            },
            {
              hidden: false,
              meta: false,
              name: "deuid",
              column: "deuid",
              type: "java.lang.String",
            },
            {
              hidden: false,
              meta: false,
              name: "dename",
              column: "dename",
              type: "java.lang.String",
            },
            {
              hidden: false,
              meta: false,
              name: "categoryuid",
              column: "categoryuid",
              type: "java.lang.String",
            },
            {
              hidden: false,
              meta: false,
              name: "categoryname",
              column: "categoryname",
              type: "java.lang.String",
            },
            {
              hidden: false,
              meta: false,
              name: "categoryoptioncomboid",
              column: "categoryoptioncomboid",
              type: "java.lang.String",
            },
            {
              hidden: false,
              meta: false,
              name: "categoryoptionuid",
              column: "categoryoptionuid",
              type: "java.lang.String",
            },
            {
              hidden: false,
              meta: false,
              name: "categoryoptionname",
              column: "categoryoptionname",
              type: "java.lang.String",
            },
          ],
          rows: [
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102162,
              "gDSaE0irZ1o",
              "Abdominal fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102163,
              "LVeLXpbet6n",
              "Abscess aspirate",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102164,
              "iMPORaNiLQF",
              "BAL",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102165,
              "rCB2iMV7YvP",
              "Bile",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102166,
              "kEAC5cyt329",
              "Biopsy",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102167,
              "EMNNhf1mkIf",
              "Blood-central catheter",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102168,
              "Gxv91tAoOYb",
              "Blood-peripheral",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102169,
              "p0jiOcpaV1p",
              "Bone",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102170,
              "IE0j3Zdy0d9",
              "Bone Marrow",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102171,
              "hZXyo4djs8n",
              "Brain abscess",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102172,
              "oY09wa31caA",
              "Cervical Swab",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102173,
              "mlboeVkCcZG",
              "CSF",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102174,
              "CfyS2c1ix7i",
              "Drain Fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102175,
              "oTezj8K9bYT",
              "Ear Swab",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102176,
              "iWKh16pVXuq",
              "Endometrium",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102177,
              "HmoGdVdGo6H",
              "Endotracheal aspirate (ETA)",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102178,
              "TO0sy0Zuwqf",
              "Ethmoidal tissue",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102179,
              "UQGvsVTLcTO",
              "Faeces",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102180,
              "eUXY0vf9PlT",
              "Fluid from sterile site",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102181,
              "FJemTzwCc05",
              "FNAC",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102182,
              "YpPD0NMdUsb",
              "Gastric fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102183,
              "jlKojdMzBEE",
              "Genital tract",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102184,
              "UIMH1Dw9Lci",
              "Hair",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102185,
              "Wc4XPSQbbQ6",
              "ICTD fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102186,
              "njbeffh4TNM",
              "Instrument",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102187,
              "YlWxPrrHl8g",
              "Intestinal fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102188,
              "Ii75ujYHuto",
              "Intracostal tube fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102189,
              "wusqmZiQsRg",
              "Intra operative bile",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102190,
              "iqqie51zu3D",
              "Intra operative fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102191,
              "gwTrCI8PH4d",
              "Iobectomy tissue",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102192,
              "ISTHnJbfyAa",
              "Joint Fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102193,
              "wgpPLmBlq6l",
              "Lung aspirate",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102194,
              "g8paJ3lBKN8",
              "Lymph node",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102195,
              "O2jW9L3sqMQ",
              "Maxillary alveolar tissue",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102196,
              "zLVVlGwzCRa",
              "Maxillary sinus",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102197,
              "I94CcnrYTrW",
              "Nail",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102198,
              "SW3dcqDBeto",
              "Nasal scrapping",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102199,
              "yo2QluIlE9r",
              "Nasal tissue",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102200,
              "k5EtIhkasQw",
              "Necrosum",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102201,
              "O49b5AZwWZo",
              "Needle aspirate",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102202,
              "sdGcyuxcIk3",
              "Ocular-deep",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102203,
              "PstPwj4qYwE",
              "Ocular-superficial",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102204,
              "eNieWxL3uoE",
              "Oral cavity crust",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102205,
              "m4Arg4vlEth",
              "Others",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102206,
              "v4lUzoUmkr2",
              "Palatal mucosa",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102207,
              "dSkfCCTZEPX",
              "Palatal scrapping",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102208,
              "VvNhzd5ut3K",
              "Pancreatic drain fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102209,
              "ifpMw000yY2",
              "Pericardial fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102210,
              "IxRGpD8z7lq",
              "Peripheral catheter-blood",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102211,
              "FgO80A7N25z",
              "Peritoneal fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102212,
              "MwBZwfXsOoc",
              "Pigtail fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102213,
              "mJH1vPH5t0p",
              "Placental Membrane",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102214,
              "PpoYHh2dxBo",
              "Pleural fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102215,
              "Yz19RVLD22o",
              "PTBD fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102216,
              "vsXC8V4Clhj",
              "Pus/exudate",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102217,
              "LicGv6Agzrl",
              "Semen",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102218,
              "ElE0Rux1JLU",
              "Sinus mass",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102219,
              "OvFwToZRZJ6",
              "Skin biopsy",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102220,
              "VEwWYU5O5MY",
              "Sputum",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102221,
              "b8HE0Dri1lb",
              "Throat swab",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102222,
              "HpeIEw4hCNX",
              "Tissue",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102223,
              "zHicP6UeSzZ",
              "Urine",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102224,
              "cUgnw8XPO5K",
              "Vaginal swab",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102225,
              "fPRKlVgSiq1",
              "Vascular Catheter tip",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102226,
              "tuzKiHrG2VC",
              "Vitreous fluid",
            ],
            [
              "NFGNB - Sample Wise",
              180831,
              "q6rN3ViZvHj",
              "Acinetobacter baumannii",
              "vgZPpD2yUly",
              "Sample",
              102227,
              "EGHnHTEQ2Wi",
              "Wound swab",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173314,
              "EjPyvyQDVOf",
              "Amikacin-Intermediate, Abdominal fluid",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173315,
              "oFVbmwuRyzJ",
              "Amikacin-Intermediate, Abscess aspirate",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173316,
              "CqNdBMJbPoE",
              "Amikacin-Intermediate, BAL",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173317,
              "WvTzVdTWvbb",
              "Amikacin-Intermediate, Bile",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173318,
              "T5Mn2why3AI",
              "Amikacin-Intermediate, Biopsy",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173319,
              "CcRUkCIyrhZ",
              "Amikacin-Intermediate, Blood-central catheter",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173320,
              "CuBogsdSWvn",
              "Amikacin-Intermediate, Blood-peripheral",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173321,
              "nJ29aod8xV9",
              "Amikacin-Intermediate, Bone",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173322,
              "pfCEGrqQxSD",
              "Amikacin-Intermediate, Bone Marrow",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173323,
              "QQiZygyqerT",
              "Amikacin-Intermediate, Brain abscess",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173324,
              "ncJ3oRJMyTw",
              "Amikacin-Intermediate, Cervical Swab",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173325,
              "ABkAAFeYQV7",
              "Amikacin-Intermediate, CSF",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173326,
              "vWGIbQgmoJF",
              "Amikacin-Intermediate, Drain Fluid",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173327,
              "GgxicspLgyR",
              "Amikacin-Intermediate, Ear Swab",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173328,
              "a7EhS0ULjsL",
              "Amikacin-Intermediate, Endometrium",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173329,
              "fOyonpw84pQ",
              "Amikacin-Intermediate, Endotracheal aspirate (ETA)",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173330,
              "Afm7NMKFM3J",
              "Amikacin-Intermediate, Ethmoidal tissue",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173331,
              "eEj5sg6CaUy",
              "Amikacin-Intermediate, Faeces",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173332,
              "RDywDiyHBZD",
              "Amikacin-Intermediate, Fluid from sterile site",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173333,
              "PuhxMKQvLo2",
              "Amikacin-Intermediate, FNAC",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173334,
              "wqirQVIyUwB",
              "Amikacin-Intermediate, Gastric fluid",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173335,
              "TSSiQLiUJRr",
              "Amikacin-Intermediate, Genital tract",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173336,
              "OT57H7G1x6y",
              "Amikacin-Intermediate, Hair",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173337,
              "VlbEwQDdPHP",
              "Amikacin-Intermediate, ICTD fluid",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173338,
              "R3WWtvIawRq",
              "Amikacin-Intermediate, Instrument",
            ],
            [
              "NFGNB - Antibiotic Wise",
              207304,
              "Wwob0qWbiyP",
              "Acinetobacter baumannii - AW",
              "ej3wbeG6uBB",
              "NFGNB",
              173339,
              "R3WWtvIawRq",
              "Amikacin-Intermediate, Intestinal fluid",
            ],
          ],
        },
      };
      var dataToBePushed = {};
      returndata.listGrid.rows.forEach(function (arrayItem, index) {
        var countOfDataElement = 0;
        var dataElementUID = arrayItem[2];
        var dataSetElements = arrayItem[7];
        var keyToBeStored =
          dataElementUID + "-" + dataSetElements + "-" + "val";
        if (dataToBePushed.hasOwnProperty(keyToBeStored)) {
          dataToBePushed[keyToBeStored] = dataToBePushed[keyToBeStored] + 1;
        } else {
          dataToBePushed[keyToBeStored] = countOfDataElement + 1;
        }

        console.log(
          "DATA to be PUSHED IN DATA ENTRY " + JSON.stringify(dataToBePushed)
        );
      });
    }
    return dataElementsEvent;
  }

  getTrackerData() {
    // var eventsData = this.getResult();
    // var dataValue = [];
    // console.log("Before Call");

    // axios
    //   .get(`../../../api/29/sqlViews/Iue75rEGLD9/data.json?paging=false`)
    //   .then((resp) => {
    //     console.log(resp);
    //   });

    // axios
    //   .get(
    //     `https://ln2.hispindia.org/amr/api/sqlViews/Nt5LQ2Gpvsc/data.json?paging=false`
    //   )
    //   .then((resp) => {
    //     console.log(resp);
    //   });

    console.log("After Call");
  }

  componentDidMount() {
    // this.getTrackerData();
    this.getResult();
    // this.getPrograms();
  }
  render() {
    return (
      <>
        <div className="row">
          <div className="col-lg-auto col-md-auto col-sm-auto col-xs-auto shadow-lg bg-white rounded">
            <OrgUnitTree onSelect={this.onSelect} onError={onError} />
          </div>
          <div className="col-lg-9 col-md-9 col-sm-9 col-xs-9">
            <DynamicComponent data={this.state.orgUnit} />
          </div>
        </div>
      </>
    );
  }
}
export default HomeComponet;
