export const GET_ORG_UNITS_DETAIL = 'GET_ORG_UNITS_DETAIL';
export const METADATA_RECEIVED = 'METADATA_RECEIVED';
export const DYNAMIC_RECEIVED_DATA = 'DYNAMIC_RECEIVED_DATA';
export const SET_EVENT_VALUES = 'SET_EVENT_VALUES';
export const UPDATE_EVENT_VALUES = 'UPDATE_EVENT_VALUES';
export const SET_PAYLOAD = 'SET_PAYLOAD';
export const PROGRAMS_RECEIVED = 'PROGRAMS_RECEIVED';
export const PROGRAMSTAGE_RECEIVED = 'PROGRAMSTAGE_RECEIVED';
export const PROGRAMSTAGE_SECTIONS_RECEIVED = 'PROGRAMSTAGE_SECTIONS_RECEIVED';
export const SET_DATA_VALUES = 'SET_DATA_VALUES';
export const SET_TEI_ATTRIBUTE = 'SET_TEI_ATTRIBUTE';
export const TRACKED_ENTITY_RECEIVED = 'TRACKED_ENTITY_RECEIVED';
export const CHECKED_VALIDATION = 'CHECKED_VALIDATION';
export const SET_PROGRAM_RULES = 'SET_PROGRAM_RULES';
export const PROGRAMSTAGE_SECTIONS_UPDATE = 'PROGRAMSTAGE_SECTIONS_UPDATE';
export const EVENT_POST = 'EVENT_POST';
export const EVENT_FAILURE = 'EVENT_FAILURE';
export const RESET = 'RESET';
export const RESET_FORM = 'RESET_FORM';



