export const GET_ORG_UNITS_DETAIL = 'GET_ORG_UNITS_DETAIL';
export const METADATA_RECEIVED = 'METADATA_RECEIVED';
export const DYNAMIC_RECEIVED_DATA = 'DYNAMIC_RECEIVED_DATA';
export const SET_EVENT_VALUES = 'SET_EVENT_VALUES';
export const UPDATE_EVENT_VALUES = 'UPDATE_EVENT_VALUES';
export const SET_PAYLOAD = 'SET_PAYLOAD';
export const PROGRAMS_RECEIVED = 'PROGRAMS_RECEIVED';
export const PROGRAMSTAGE_RECEIVED = 'PROGRAMSTAGE_RECEIVED';
export const PROGRAMSTAGE_SECTIONS_RECEIVED = 'PROGRAMSTAGE_SECTIONS_RECEIVED';
export const SET_DATA_VALUES = 'SET_DATA_VALUES';
export const SET_TEI_ATTRIBUTE = 'SET_TEI_ATTRIBUTE';
export const TRACKED_ENTITY_RECEIVED = 'TRACKED_ENTITY_RECEIVED';
export const CHECKED_VALIDATION = 'CHECKED_VALIDATION';
export const SET_PROGRAM_RULES = 'SET_PROGRAM_RULES';
export const PROGRAMSTAGE_SECTIONS_UPDATE = 'PROGRAMSTAGE_SECTIONS_UPDATE';
export const EVENT_POST = 'EVENT_POST';
export const EVENT_FAILURE = 'EVENT_FAILURE';
export const RESET = 'RESET';
export const RESET_FORM = 'RESET_FORM';
export const LOADING_PAGE = 'LOADING_PAGE';
export const FETCH_CONDITIONAL_OU = 'FETCH_CONDITIONAL_OU';
export const SET_PROGRAM_RULES_CONDITION = 'SET_PROGRAM_RULES_CONDITION';
export const PROGRAM_RULE_MERGE = 'PROGRAM_RULE_MERGE';
export const SET_MENDATORY_DATAELEMENTS = 'SET_MENDATORY_DATAELEMENTS';
export const CHECK_MANDATORY = 'CHECK_MANDATORY';
export const TRANSLATION_DATAELEMENTS = 'TRANSLATION_DATAELEMENTS';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const DATETYPE_DATAELEMENTS = 'DATETYPE_DATAELEMENTS';











